server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    # 最大线程数，最好大于max-connections，否则会出现占位等待情况
    max-threads: 1025
    # 等待队列长度，默认100
    accept-count: 100
    # 最大连接数，相当于最大可同时执行任务的数量，如果高于max-threads会出现等待线程情况
    max-connections: 1024
    # 初始至少会建立的线程数
    min-spare-threads: 100
    # Connector从接受连接到提交URI的等

#是否激活 swagger true or false
swagger:
  enable: true


spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 1000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

